### ISSUE TITLE
(Vibrancegui) Cs:Go problem with weapons and profile pictures! 

### ISSUE THREAD

**Issue by Viljami17** [juvlarN/vibranceGUI#22]
Hello! Anyone else got this problem or is it normal. In **CS:GO** match in buy menu i see blue under the weapon and profile pictures look so terrible. How to fix this? 
Thanks for advice!
- Ezfin from yt

**Comment by juvlarN** [comment]
Hi, 

using Digital Vibrance for NVIDIA -- or the equivalent Saturation for AMD -- might introduce visual artificats due to the nature of these algorithms. While both of the functions try to enhance the visual appearance of the displayed image, both can produce weird artifacts when postprocessing the frames. 

You could try and lower the in-game value in vibranceGUI to lower the amount of artifacts you see. However, people tend to "accept" these artifacts. Being able to spot enemies easier is more important than having good looking profile pictures or the like for most users ;-) 

This is not a problem with vibranceGUI. The program is utilizing your driver to change the values of the previously named algorithms. Whether these artifacts occur or not is beyond the scope of vibranceGUI. 

Greets
