### ISSUE TITLE
Release versions on GitHub

### ISSUE THREAD

**Issue by ElPumpo** [juvlarN/vibranceGUI#24]
Why are no releases (exe files) available on https://github.com/juvlarN/vibranceGUI/releases ?

**Comment by Sorashi** [comment]
I think it's because

1. Creating a release creates a tag, which isn't part of the development process of the repo maintainer(s)
2. This repo is meant to be for people interested in the source code or collaboration, which means that they probably can make a release (compile) themselves
3. Any client can download the binaries from the [official homepage](http://vibrancegui.com/) of this project
