### ISSUE TITLE
CS:GO, green tint with 16:9 resolutions?

### ISSUE THREAD

**Issue by MarcysVonEylau** [juvlarN/vibranceGUI#26]
Vibrance greater than 200 introduces green tint. 300 everyting is green.

Only happens in CS:GO at 16:9 resolutions set in settings. 4:3 and 16:10 is okay.

Graphics: AMD R9 280;
Driver Version: 16.40.2311-160916a-307259E;

**Comment by juvlarN** [comment]
Hi,

this is not a bug but a feature.
Your AMD drivers can only go to 200, while vibranceGUI can force the value up to 300. 
300% can introduce artifacts as you noticed, but this is out of control of vibranceGUI. 
Use 200% if you prefer the looks of 200%.

**Comment by MarcysVonEylau** [comment]
But it's okay for 4:3 and 16:9 resolutions... And it worked before :/

**Comment by juvlarN** [comment]
Well, I don't know sorry. When the value is set, it's set. The GPU will have to do the rest. Ask this question to the AMD support, although they probably won't give you any support because you're using a value not allowed/wanted in their AMD drivers. If it worked before, you might try to reinstall the old AMD drivers you had back then.
