### ISSUE TITLE
VibranceGui not working in fullscreen csgo

### ISSUE THREAD

**Issue by TheRealSlimshady1** [juvlarN/vibranceGUI#42]
Okay so i use Windows 8.1 Pro, Gtx 980, and vibrance wont work only in windowed mode. It works everywhere else, just in fullscreen not. What can i do?

**Comment by juvlarN** [comment]
Which game are you trying?
Did you try it in another fullscreen game too?

**Comment by TheRealSlimshady1** [comment]
Im trying in CS:Go, but it works on fullscreen Leauge Of Legends.

**Comment by juvlarN** [comment]
Yeah this is a known problem in CS:GO. 
Since the update like 1 month ago, Valve broke the Digital Vibrance / Saturation effect for some users. It still works for most of the users. But for some it does not work. 

To show that this is not related to vibranceGUI:

- Close vibranceGUI
- Go to NVIDIA Control Panel
- Go to Display -> Desktop Color Settings -> 3. Digital Vibrance 
- Set value to 100%, your Windows will get a lot of vibrancy.
- Launch CS:GO (Fullscreen) -> Nothing will happen

**Comment by TheRealSlimshady1** [comment]
I did that too already.

**Comment by TheRealSlimshady1** [comment]
And nothing happend in csgo, only in windows.

**Comment by TheRealSlimshady1** [comment]
SO?

**Comment by juvlarN** [comment]
so... this is not related to vibranceGUI :-)

**Comment by TheRealSlimshady1** [comment]
And what can i do about it?

**Comment by juvlarN** [comment]
Can you try the newest beta on vibrancegui.com/vibrance/beta ?

**Comment by j4wn** [comment]
2.3.0.5 works for me on Windows 10 (1703) w/ NVIDIA 384.94 (full screen CS:GO)

I'd say this was related to detection? I experienced this in 2.3.0.3 but @TheRealSlimshady1 can you confirm?

**Comment by jibiox** [comment]
@juvlarN I had the same issue both nvidia & vibrancegui stopped working in-game fullscreen for me AFTER i upgraded to my BenQ xl2411z 144Hz screen, however the beta you linked fixed it for me so thanks !

**Comment by juvlarN** [comment]
Looks like this is resolved! Thanks for your input guys
