### ISSUE TITLE
VibranceGUI's minimum is 50% instead of 0%.

### ISSUE THREAD

**Issue by nejtilsvampe** [juvlarN/vibranceGUI#62]
Can we please get an option to at least go lower than 50%?

The usecase for me is I have a monitor in which I have maxed color saturation, which is perfect for gaming, however when watching movies it is going overboard.

I would like to go less than 50% in the GUI on my desktop, so that I can maximize the color saturation in games without having to fiddle with the monitor settings every time.

Moreover I can even imagine a usecase where you'd want to play a game in black and white, just for the hell of it.

**Comment by juvlarN** [comment]
The NVIDIA API, which you are referring to, limits the digital vibrance values from 0 to 63 internally.
0 represents 50% and 63 represents 100% in the NVIDIA Control Panel.
It is not possible to **set** values below or higher than these values.
The API does also not return any negative value when **retrieving** the current value from the NVIDIA API. When you change the digital vibrance value in your Control Panel to say 10%, the API will still return value 0 (which equals 50% when setting it with an API call). 
Hence this feature request is not possible with the current API version. The NVIDIA API is not frequently updated, in fact it has barely been updated since several years, so this is unlikely to be added in the near future.
