### ISSUE TITLE
VibranceGUI only seems to work if CSGO is set to full screen windowed?

### ISSUE THREAD

**Issue by jassibacha** [juvlarN/vibranceGUI#7]
As the title reads, it only loads when in Fullscreen Windowed + Windowed (I play Fullscreen 1024x768)

I've attached my settings, let me know if you need anything else from me. Current setup is 2 670GTX's set as "All DIsplays" running on 3 monitors.

![untitled-1](https://cloud.githubusercontent.com/assets/3331801/6770478/3e00ecc2-d07e-11e4-8060-807fec0ca84b.png)

**Comment by juvlarN** [comment]
Hi,

so you are running two graphic cards? Can you temporarily disable one of them and look if the bug still occurs? It probably has something to do with Windows using your second indexed graphics card rather than the first one. This is something I haven't kept in mind while developing the vibranceDLL. I have an fix for this in mind though. But first of all, please check whether your second graphics card is the actual cause of the problem. 

Thanks

**Comment by jassibacha** [comment]
After more testing I figured it out, I had an HDMI cord plugged into my TV and was cloning the display and that was interfering. Once I unplugged that cable it was working correctly in fullscreen.

Awesome program btw!

**Comment by juvlarN** [comment]
Alright! I'll close this
